# Generated by Django 5.1.2 on 2024-10-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='job_title',
            field=models.CharField(choices=[('tera', 'Терапевт'), ('teeth', 'Стоматолог'), ('ped', 'Ортопед'), ('nev', 'Невролог'), ('pshy', 'Психиатр'), ('oto', 'Отоларинголог'), ('kardio', 'Кардиолог'), ('der', 'Дерматолог'), ('gen', 'Гинеколог'), ('gas', 'Гастроэнтеролог'), ('diet', 'Диетолог')], max_length=100, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_record', models.DateTimeField(verbose_name='Дата и время записи')),
                ('diagnosis', models.CharField(blank=True, choices=[('temp', 'Температура'), ('cough', 'Кашель'), ('rn', 'Насморк'), ('highpressure', 'Повышенное давление'), ('head', 'Головокружение'), ('gas', 'Гастрит'), ('ozh', 'Ожирение'), ('inf', 'Инфаркт'), ('dep', 'Депрессия')], max_length=100, null=True, verbose_name='Диагноз')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iddoc', to='hosp.doctors', verbose_name='ID доктора')),
                ('id_hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idhosp', to='hosp.hospitals', verbose_name='ID поликлиники')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idpat', to='hosp.patient', verbose_name='ID пациента')),
            ],
        ),
    ]
