# Generated by Django 5.1.2 on 2024-10-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0002_alter_doctors_job_title_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='hospitals',
            options={'ordering': ['title', 'adress'], 'verbose_name': 'Поликлиника', 'verbose_name_plural': 'Поликлиники'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Заведующий', 'verbose_name_plural': 'Заведующие'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name', 'surname'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациент'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date_time_record'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='record',
            name='diagnosis',
            field=models.CharField(blank=True, choices=[('temp', 'Температура'), ('cough', 'Кашель'), ('rn', 'Насморк'), ('highpressure', 'Повышенное давление'), ('head', 'Головокружение'), ('gas', 'Гастрит'), ('ozh', 'Ожирение'), ('inf', 'Инфаркт'), ('dep', 'Депрессия'), ('undef', 'Диагноз не определен')], max_length=100, null=True, verbose_name='Диагноз'),
        ),
    ]
